trigger:
  - master

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(1)(27926aee-9af8-4228-8602-054d257c26fd)'
    appType: 'functionAppLinux'
    appName: 'sjoerds-portfolio'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'NODE|14'
    startUpCommand: 'npm run build'
